### ISSUE TITLE
Spark 2

### ISSUE THREAD

**Issue by marvi** [MetaCenterCloudPuppet/cesnet-spark#1]
Do you have plans to support Spark 2 with your Puppet solution?

Cloudera CDH has not included Spark 2 as RPM packages. They just ship their parcel format (http://archive.cloudera.com/spark2/parcels/). I got the feeling when talking to some Cloudera engineers that parcels are the way they are recommending for deploying CDH. Have you considered looking at another distribution like HDP or even Bigtop going forward?

**Comment by valtri** [comment]
I don't have the plans for Spark 2 right now. But we will need to plan the big HW upgrade + upgrade strategy for our cluster soon. If we will keep the "puppet way", switching the distribution is the right question.

The situation with Cloudera is even worse in our use-case - they aren't updating the Hadoop core version, but they also don't backport fixes in upstream we need (Java 8 + kerberos support) and ignore our bug reports with patches. So we're rebuilding CDH with our patches with each update...

Both Bigtop and Hortonworks look interesting.

**Comment by epleterte** [comment]
I am running Spark 2 with this module - currently on Spark 2.1.0. It seems to work just fine :)
I am also building the stack myself using Bigtop. I am still using Cassandra (cassandra30) from the Datastax repo, but the rest of the stack (everything else) from the Cloudera repos I have replaced with my own repo.

**Comment by marvi** [comment]
@epleterte Did you have to modify Cesnet's modules to get it to run with Bigtop packages or did it work out of the box?

**Comment by valtri** [comment]
Due to BigTop distribution: there were slight problem with not using /etc/default/spark. It shoud work with the new version of cesnet-spark 1.2.2.

And Spark 2 seems working fine.
